sudo: false
language: node_js
node_js:
  - "node"
install:  npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
deploy:
  provider: surge
  project: ./
  skip_cleanup: true
  on: master
